SCR_AvailableActionsDisplay {
 m_aActions {
  SCR_AvailableActionContext "{6922E58AE70FA4D2}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70FA4E4}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70FA4E6}" {
    }
   }
   m_sTag "PILOT_CAMERA_UP"
   m_sAction "PilotCameraUp"
   m_sName "Pilot Camera Up"
  }
  SCR_AvailableActionContext "{6922E58AE70FA4E0}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70FA4E3}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70FA4E2}" {
    }
   }
   m_sTag "PILOT_CAMERA_DOWN"
   m_sAction "PilotCameraDown"
   m_sName "Pilot Camera Down"
  }
  SCR_AvailableActionContext "{6922E58AE70FA49D}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70FEBA8}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70FEBA9}" {
    }
   }
   m_sTag "PILOT_CAMERA_LEFT"
   m_sAction "PilotCameraLeft"
   m_sName "Pilot Camera Left"
  }
  SCR_AvailableActionContext "{6922E58AE70FEBAA}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70FEBAB}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70FEBAC}" {
    }
   }
   m_sTag "PILOT_CAMERA_RIGHT"
   m_sAction "PilotCameraRight"
   m_sName "Pilot Camera Right"
  }
  SCR_AvailableActionContext "{6922E58AE70FEBAD}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70FEBA6}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70FEBA7}" {
    }
   }
   m_sTag "PILOT_CAMERA_ZOOM"
   m_sAction "PilotCameraZoom"
   m_sName "Pilot Camera Zoom"
  }
  SCR_AvailableActionContext "{6922E58AE70FEBB8}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70FEE22}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70FEE20}" {
    }
   }
   m_sTag "PILOT_CAMERA_LOCK"
   m_sAction "PilotCameraLock"
   m_sName "Pilot Camera Lock"
  }
  SCR_AvailableActionContext "{6922E58AE70E0135}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70E0134}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70E0133}" {
    }
   }
   m_sTag "PILOT_CAMERA_VISION_CYCLE"
   m_sAction "PilotCameraVisionMode"
   m_sName "Change pilot camera vision mode"
  }
  SCR_AvailableActionContext "{6922E58AE70E0132}" {
   m_aConditions {
    RVX_HasPilotCameraCondition "{6922E58AE70E0131}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70E0130}" {
    }
   }
   m_sTag "PILOT_CAMERA_FORWARD"
   m_sAction "PilotCameraForward"
   m_sName "Pilot Camera Forward"
  }
  SCR_AvailableActionContext "{6922E58AE70E0107}" {
   m_aConditions {
    RVX_IsAimingSoflam "{6922E58AE70E0106}" {
    }
   }
   m_sTag "LASER_DESIGNATOR_TOGGLE"
   m_sAction "LaserDesignatorToggle"
   m_sName "Laser ON"
  }
  SCR_AvailableActionContext "{6922E58AE70E0105}" {
   m_aConditions {
    RVX_HasMisileCameraComponent "{6922E58AE70E0104}" {
    }
    SCR_CharacterIsInVehicleCondition "{6922E58AE70EA636}" {
    }
   }
   m_sTag "TOGGLE_MISSILE_CAMERA"
   m_sAction "MissleCameraToggle"
   m_sName "Toggle missile camera"
  }
 }
}