ActionManager {
 Actions {
  Action PilotCameraUp {
   InputSource InputSourceSum "{6922E58AF173A7E7}" {
    Sources {
     InputSourceValue "{6922E58AF173A7ED}" {
      FilterPreset "down"
      Input "keyboard:KC_NUMPAD8"
      Filter InputFilterValue "{6922E58AF173A7EF}" {
      }
     }
    }
   }
  }
  Action PilotCameraDown {
   InputSource InputSourceSum "{6922E58AF173A7E8}" {
    Sources {
     InputSourceValue "{6922E58AF173A7EB}" {
      FilterPreset "down"
      Input "keyboard:KC_NUMPAD2"
      Filter InputFilterValue "{6922E58AF173A7EA}" {
      }
     }
    }
   }
  }
  Action PilotCameraLeft {
   InputSource InputSourceSum "{6922E58AF173A794}" {
    Sources {
     InputSourceValue "{6922E58AF173A797}" {
      FilterPreset "down"
      Input "keyboard:KC_NUMPAD4"
      Filter InputFilterValue "{6922E58AF173A796}" {
      }
     }
    }
   }
  }
  Action PilotCameraRight {
   InputSource InputSourceSum "{6922E58AF173A790}" {
    Sources {
     InputSourceValue "{6922E58AF17389A0}" {
      FilterPreset "down"
      Input "keyboard:KC_NUMPAD6"
      Filter InputFilterValue "{6922E58AF17389A2}" {
      }
     }
    }
   }
  }
  Action PilotCameraZoom {
   InputSource InputSourceSum "{6922E58AF17389AC}" {
    Sources {
     InputSourceValue "{6922E58AF17389B4}" {
      FilterPreset "click"
      Input "keyboard:KC_NUMPAD0"
      Filter InputFilterValue "{6922E58AF17389B7}" {
      }
     }
    }
   }
  }
  Action PilotCameraLock {
   InputSource InputSourceSum "{6922E58AF17389B1}" {
    Sources {
     InputSourceValue "{6922E58AF17389B0}" {
      FilterPreset "toggle"
      Input "keyboard:KC_NUMPAD5"
      Filter InputFilterClick "{6922E58AF173ECF2}" {
      }
     }
    }
   }
  }
  Action PilotCameraForward {
   InputSource InputSourceSum "{6922E58AF173ECF0}" {
    Sources {
     InputSourceValue "{6922E58AF173ECFF}" {
      FilterPreset "hold"
      Input "keyboard:KC_NUMPAD5"
      Filter InputFilterHold "{6922E58AF173ECFE}" {
       HoldDuration 500
      }
     }
    }
   }
  }
  Action PilotCameraVisionMode {
   InputSource InputSourceSum "{6922E58AF173ECFC}" {
    Sources {
     InputSourceCombo "{6922E58AF173ECFB}" {
      FilterPreset "toggle"
      Sources {
       InputSourceValue "{6922E58AF173ECFA}" {
        Input "keyboard:KC_LMENU"
       }
       InputSourceValue "{6922E58AF173ECC1}" {
        Input "keyboard:KC_V"
       }
      }
     }
    }
   }
  }
  Action LaserDesignatorToggle {
   InputSource InputSourceSum "{6922E58AF173ECCF}" {
    Sources {
     InputSourceValue "{6922E58AF173ECCE}" {
      FilterPreset "click"
      Input "keyboard:KC_T"
      Filter InputFilterValue "{6922E58AF173ECCD}" {
      }
     }
    }
   }
  }
  Action MissleCameraToggle {
   InputSource InputSourceSum "{6922E58AF173ECCC}" {
    Sources {
     InputSourceValue "{6922E58AF173ECCB}" {
      FilterPreset "click"
      Input "keyboard:KC_N"
      Filter InputFilterValue "{6922E58AF173ECCA}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs {
    "LaserDesignatorToggle"
   }
  }
  ActionContext HelicopterContext {
   ActionRefs {
    "PilotCameraUp"
    "PilotCameraDown"
    "PilotCameraLeft"
    "PilotCameraRight"
    "PilotCameraLock"
    "PilotCameraForward"
    "PilotCameraZoom"
    "PilotCameraVisionMode"
    "MissleCameraToggle"
    "LaserDesignatorToggle"
   }
  }
  ActionContext CharacterCompartmentContext {
   ActionRefs {
    "PilotCameraUp"
    "PilotCameraDown"
    "PilotCameraLeft"
    "PilotCameraRight"
    "PilotCameraLock"
    "PilotCameraForward"
    "PilotCameraZoom"
    "PilotCameraVisionMode"
   }
  }
 }
}