SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{6922E58AF5BFABEE}" {
   m_sName "RVX"
   m_sDisplayName "RVX"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{6922E58AF5BFABF7}" {
     m_sActionName "separator"
     m_sDisplayName "Controls"
    }
    SCR_KeyBindingEntry "{6922E58AF5BFABF5}" {
     m_sActionName "PilotCameraUp"
     m_sDisplayName "Pilot Camera Up"
     m_sPreset "down"
    }
    SCR_KeyBindingEntry "{6922E58AF5BFABF4}" {
     m_sActionName "PilotCameraDown"
     m_sDisplayName "Pilot Camera Down"
     m_sPreset "down"
    }
    SCR_KeyBindingEntry "{6922E58AF5BFABF3}" {
     m_sActionName "PilotCameraLeft"
     m_sDisplayName "Pilot Camera Left"
     m_sPreset "down"
    }
    SCR_KeyBindingEntry "{6922E58AF5BFABF2}" {
     m_sActionName "PilotCameraRight"
     m_sDisplayName "Pilot Camera Right"
     m_sPreset "down"
    }
    SCR_KeyBindingEntry "{6922E58AF5BFABF1}" {
     m_sActionName "PilotCameraZoom"
     m_sDisplayName "Pilot camera cycle zoom"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6922E58AF5BF8FA0}" {
     m_sActionName "PilotCameraLock"
     m_sDisplayName "Pilot Camera Lock"
     m_sPreset "toggle"
    }
    SCR_KeyBindingEntry "{6922E58AF5BF8FA1}" {
     m_sActionName "PilotCameraForward"
     m_sDisplayName "Pilot Camera Forward"
     m_sPreset "hold"
    }
    SCR_KeyBindingEntry "{6922E58AF5BF8FAE}" {
     m_sActionName "PilotCameraVisionMode"
     m_sDisplayName "Change Pilot Camera Vision"
     m_sPreset "toggle"
    }
    SCR_KeyBindingEntry "{6922E58AF5BF8FAF}" {
     m_sActionName "MissleCameraToggle"
     m_sDisplayName "Toggle missile camera"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6922E58AF5BF8FAC}" {
     m_sActionName "LaserDesignatorToggle"
     m_sDisplayName "Toggle laser designator (SOFLAM)"
     m_sPreset "click"
    }
   }
  }
 }
}